//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALTSCANUI.AtlscanRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ATLSCANService.Contracts")]
    [System.SerializableAttribute()]
    public partial class ServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AtlscanRef.IZipService")]
    public interface IZipService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZipService/ProcessZipManual", ReplyAction="http://tempuri.org/IZipService/ProcessZipManualResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ALTSCANUI.AtlscanRef.ServiceFault), Action="http://tempuri.org/IZipService/ProcessZipManualServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ATLSCANService.Contracts")]
        string ProcessZipManual(string zipFileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZipService/ProcessZipManual", ReplyAction="http://tempuri.org/IZipService/ProcessZipManualResponse")]
        System.Threading.Tasks.Task<string> ProcessZipManualAsync(string zipFileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZipService/ProcessZipBatch", ReplyAction="http://tempuri.org/IZipService/ProcessZipBatchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ALTSCANUI.AtlscanRef.ServiceFault), Action="http://tempuri.org/IZipService/ProcessZipBatchServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/ATLSCANService.Contracts")]
        string ProcessZipBatch();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZipService/ProcessZipBatch", ReplyAction="http://tempuri.org/IZipService/ProcessZipBatchResponse")]
        System.Threading.Tasks.Task<string> ProcessZipBatchAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZipService/SearchFile", ReplyAction="http://tempuri.org/IZipService/SearchFileResponse")]
        string[] SearchFile(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZipService/SearchFile", ReplyAction="http://tempuri.org/IZipService/SearchFileResponse")]
        System.Threading.Tasks.Task<string[]> SearchFileAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZipService/DownloadFile", ReplyAction="http://tempuri.org/IZipService/DownloadFileResponse")]
        byte[] DownloadFile(string relativePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZipService/DownloadFile", ReplyAction="http://tempuri.org/IZipService/DownloadFileResponse")]
        System.Threading.Tasks.Task<byte[]> DownloadFileAsync(string relativePath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZipServiceChannel : ALTSCANUI.AtlscanRef.IZipService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZipServiceClient : System.ServiceModel.ClientBase<ALTSCANUI.AtlscanRef.IZipService>, ALTSCANUI.AtlscanRef.IZipService {
        
        public ZipServiceClient() {
        }
        
        public ZipServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZipServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZipServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZipServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ProcessZipManual(string zipFileName) {
            return base.Channel.ProcessZipManual(zipFileName);
        }
        
        public System.Threading.Tasks.Task<string> ProcessZipManualAsync(string zipFileName) {
            return base.Channel.ProcessZipManualAsync(zipFileName);
        }
        
        public string ProcessZipBatch() {
            return base.Channel.ProcessZipBatch();
        }
        
        public System.Threading.Tasks.Task<string> ProcessZipBatchAsync() {
            return base.Channel.ProcessZipBatchAsync();
        }
        
        public string[] SearchFile(string fileName) {
            return base.Channel.SearchFile(fileName);
        }
        
        public System.Threading.Tasks.Task<string[]> SearchFileAsync(string fileName) {
            return base.Channel.SearchFileAsync(fileName);
        }
        
        public byte[] DownloadFile(string relativePath) {
            return base.Channel.DownloadFile(relativePath);
        }
        
        public System.Threading.Tasks.Task<byte[]> DownloadFileAsync(string relativePath) {
            return base.Channel.DownloadFileAsync(relativePath);
        }
    }
}
